package proxy

import (
	"bufio"
	"bytes"
	"fmt"
	"net/netip"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"ipv6-proxy-manager/internal/model"
)

var credentialPattern = regexp.MustCompile(`^[A-Za-z0-9._@-]{4,64}$`)

func ValidateCredential(value, field string) error {
	if !credentialPattern.MatchString(value) {
		return fmt.Errorf("%s must be 4-64 characters and use only letters, numbers, dot, underscore, @ or hyphen", field)
	}
	return nil
}

func RenderConfig(proxies []model.Proxy) ([]byte, error) {
	return renderConfig(proxies, true)
}

// RenderEngineConfig renders one worker's configuration. Non-empty workers do
// not need the loopback keepalive listener; omitting it lets multiple 3proxy
// workers run side by side without all trying to bind port 65535.
func RenderEngineConfig(proxies []model.Proxy, keepalive bool) ([]byte, error) {
	return renderConfig(proxies, keepalive)
}

func renderConfig(proxies []model.Proxy, keepalive bool) ([]byte, error) {
	var enabled []model.Proxy
	users := make(map[string]string)
	ports := make(map[int]struct{})
	for _, p := range proxies {
		if !p.Enabled {
			continue
		}
		if err := ValidateCredential(p.Username, "username"); err != nil {
			return nil, fmt.Errorf("port %d: %w", p.Port, err)
		}
		if err := ValidateCredential(p.Password, "password"); err != nil {
			return nil, fmt.Errorf("port %d: %w", p.Port, err)
		}
		if p.Port < 1024 || p.Port > 65535 {
			return nil, fmt.Errorf("invalid proxy port %d", p.Port)
		}
		if _, duplicate := ports[p.Port]; duplicate {
			return nil, fmt.Errorf("duplicate proxy port %d", p.Port)
		}
		ports[p.Port] = struct{}{}
		if ip, err := netip.ParseAddr(p.Host); err != nil || !ip.Is4() {
			return nil, fmt.Errorf("port %d has invalid IPv4 host", p.Port)
		}
		if ip, err := netip.ParseAddr(p.IPv6); err != nil || !ip.Is6() {
			return nil, fmt.Errorf("port %d has invalid outbound IPv6", p.Port)
		}
		if old, exists := users[p.Username]; exists && old != p.Password {
			return nil, fmt.Errorf("username %q has conflicting passwords", p.Username)
		}
		users[p.Username] = p.Password
		enabled = append(enabled, p)
	}
	sort.Slice(enabled, func(i, j int) bool { return enabled[i].Port < enabled[j].Port })

	var out bytes.Buffer
	out.WriteString("# Generated by IPv6 Proxy Manager. Manual changes are overwritten.\n")
	// maxconn applies to every listener, not to the whole process. Keeping it
	// bounded prevents thousands of listeners from advertising an impossible
	// aggregate connection limit on small VPS instances.
	out.WriteString("maxconn 16\n")
	out.WriteString("nserver 1.1.1.1\n")
	out.WriteString("nserver 8.8.8.8\n")
	out.WriteString("nscache 65536\n")
	if keepalive {
		// Keep the engine alive before the first real proxy is created. Port 65535
		// is loopback-only and reserved by the allocator.
		out.WriteString("auth none\n")
		out.WriteString("socks -p65535 -i127.0.0.1\n")
		out.WriteString("flush\n")
	}
	out.WriteString("auth strong\n")
	if len(users) > 0 {
		usernames := make([]string, 0, len(users))
		for username := range users {
			usernames = append(usernames, username)
		}
		sort.Strings(usernames)
		for _, username := range usernames {
			// 3proxy has a finite configuration command-line buffer. A single
			// users command containing thousands of credentials is truncated and
			// the remainder is parsed as an unknown command. Multiple users
			// commands are explicitly supported, so keep every line small.
			fmt.Fprintf(&out, "users %s:CL:%s\n", username, users[username])
		}
	}
	for _, p := range enabled {
		fmt.Fprintf(&out, "allow %s\n", p.Username)
		// 3proxy adds -S to its 48 KiB base stack. A negative adjustment reaches
		// Linux PTHREAD_STACK_MIN and keeps thousands of idle listeners viable
		// on a 1 GB VPS while the built-in resolver avoids libc resolver calls.
		fmt.Fprintf(&out, "socks -S-32768 -6 -n -a -p%d -i%s -e%s\n", p.Port, p.Host, p.IPv6)
		out.WriteString("flush\n")
	}
	return out.Bytes(), nil
}

func FormatList(proxies []model.Proxy, onlyLive bool) []byte {
	ordered := append([]model.Proxy(nil), proxies...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Port < ordered[j].Port })
	var out bytes.Buffer
	for _, p := range ordered {
		if onlyLive && (!p.Enabled || p.Status != "live") {
			continue
		}
		fmt.Fprintf(&out, "%s:%d:%s:%s\n", p.Host, p.Port, p.Username, p.Password)
	}
	return out.Bytes()
}

type ListEntry struct {
	Host     string
	Port     int
	Username string
	Password string
}

func ParseList(text string) ([]ListEntry, error) {
	var entries []ListEntry
	scanner := bufio.NewScanner(strings.NewReader(text))
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		parts := strings.Split(line, ":")
		if len(parts) != 4 {
			return nil, fmt.Errorf("line %d must use HOST:PORT:USERNAME:PASSWORD", lineNumber)
		}
		port, err := strconv.Atoi(parts[1])
		if err != nil || port < 1 || port > 65535 {
			return nil, fmt.Errorf("line %d has an invalid port", lineNumber)
		}
		if ip, err := netip.ParseAddr(parts[0]); err != nil || !ip.Is4() {
			return nil, fmt.Errorf("line %d has an invalid IPv4 host", lineNumber)
		}
		entries = append(entries, ListEntry{Host: parts[0], Port: port, Username: parts[2], Password: parts[3]})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("the proxy list is empty")
	}
	return entries, nil
}

type ImportedService struct {
	Host string
	Port int
	IPv6 string
}

func Parse3ProxyServices(config []byte) map[int]ImportedService {
	services := make(map[int]ImportedService)
	scanner := bufio.NewScanner(bytes.NewReader(config))
	for scanner.Scan() {
		fields := strings.Fields(strings.TrimSpace(scanner.Text()))
		if len(fields) < 2 || fields[0] != "socks" {
			continue
		}
		var service ImportedService
		for _, field := range fields[1:] {
			switch {
			case strings.HasPrefix(field, "-p"):
				service.Port, _ = strconv.Atoi(strings.TrimPrefix(field, "-p"))
			case strings.HasPrefix(field, "-i"):
				service.Host = strings.TrimPrefix(field, "-i")
			case strings.HasPrefix(field, "-e"):
				service.IPv6 = strings.TrimPrefix(field, "-e")
			}
		}
		if service.Port > 0 && service.IPv6 != "" {
			services[service.Port] = service
		}
	}
	return services
}
